/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transapp;

/**
 *
 * @author mohamed chagour
 */


import java.awt.List;
import java.io.File;
import java.io.IOException;

import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTMLDocument.Iterator;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;


public class Consult extends javax.swing.JFrame {

    /**
     * Creates new form Consult
     */
    public Consult() {
        initComponents();
        this.setTitle("Consulter");
	this.setSize(930,500);
	this.setLocationRelativeTo(null);
        jButton2.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Téléphone", "Date de prise", "Poids", "Taille", "Destination", "Etat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));
        jPanel3.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Prenom:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(310, 40, 100, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Nom:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 40, 70, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(150, 40, 140, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(430, 40, 170, 40);

        jButton2.setText("Rechercher");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(650, 30, 130, 30);

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(830, 90, 90, 30);

        jButton4.setText("Afficher tout");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(650, 80, 130, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Welcome W = new Welcome();
        W.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setRowCount(0);
			String test11 = "false";
                        
			try {
                            //Take the XML File    
		         File inputFile = new File("input.xml");
		         DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
		         DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
		         Document doc = dBuilder.parse(inputFile);
		         doc.getDocumentElement().normalize();
		         //Make a list of all the elements with name in the input 
		         NodeList nList = doc.getElementsByTagName("Livraison");
		         
		         //Seeing the Elements one by one for any possible Modification
		         for (int temp = 0; temp < nList.getLength(); temp++) {
		            Node nNode = nList.item(temp);
		            
		            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
		               Element eElement = (Element) nNode;
                               //Testing if our Element exists     
                               if (jTextField1.getText().equals("") &&
                                   jTextField2.getText().equals("")){
                                   JOptionPane.showMessageDialog(null, "Cette Livrasion n'existe pas");
                                   break;
                               }
                               
                               // Testing on the Last Name                              
                               if (jTextField2.getText().equals("")
                                   ){
                                   //Surshing with the First Name
                                   if ( jTextField1.getText().equals(eElement
                                            .getElementsByTagName("Nom")
                                            .item(0).getTextContent())
                                             
				                  ) {
                                   
                                                model.addRow(new Object[]{eElement
                                                            .getElementsByTagName("Nom")
                                                            .item(0).getTextContent(), 
                                                             eElement
                                                            .getElementsByTagName("Prenom")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Telephone")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Date")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Poids")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Taille")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Destination")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Etat")
                                                            .item(0).getTextContent()
                                                             });

                                                             test11="true";	
                                                             
				            	   
		               		
                                    }
                               }
                               //Testing if the Last Name Exists
                               if (jTextField1.getText().equals("")
                                   ){
                                        //Searching with the First Name
                                        if ( jTextField2.getText().equals(eElement
                                            .getElementsByTagName("Prenom")
                                            .item(0).getTextContent())
                                             
				                  ) {
                                   
                                                model.addRow(new Object[]{eElement
                                                            .getElementsByTagName("Nom")
                                                            .item(0).getTextContent(), 
                                                             eElement
                                                            .getElementsByTagName("Prenom")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Telephone")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Date")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Poids")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Taille")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Destination")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Etat")
                                                            .item(0).getTextContent()
                                                             });

                                                             test11="true";	
                                                             
                                    }
                                
                               }
                                
                                //testing with bothe First Name and Last name as input
                                if ( jTextField1.getText().equals(eElement
                                       .getElementsByTagName("Nom")
                                       .item(0).getTextContent())
                                             && 
                                       jTextField2.getText().equals(eElement
                                                       .getElementsByTagName("Prenom")
                                                       .item(0).getTextContent()) 
                                             
				                  ) {
                                   
                                                model.addRow(new Object[]{eElement
                                                            .getElementsByTagName("Nom")
                                                            .item(0).getTextContent(), 
                                                             eElement
                                                            .getElementsByTagName("Prenom")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Telephone")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Date")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Poids")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Taille")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Destination")
                                                            .item(0).getTextContent(),
                                                             eElement
                                                            .getElementsByTagName("Etat")
                                                            .item(0).getTextContent()
                                                             });

                                                             test11="true";	
                                    }
		               
		               }
		         }
                         if(test11.equals("false"))
		        	 JOptionPane.showMessageDialog(null, "Cette Livrasion n'existe pas");
          	   	 System.out.println(test11);
                         
                         
		      } catch (Exception ex) {
		         ex.printStackTrace();
		      }//----------------------------------------------------------------
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Taking the Model Of our JTable 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        //We make our jTable Empty
			 model.setRowCount(0);
			try {
                         //Take the XML File    
		         File inputFile = new File("input.xml");
		         DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
		         DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
		         Document doc = dBuilder.parse(inputFile);
		         doc.getDocumentElement().normalize();
                         
		         //Make a list of all the elements with name in the input 
		         NodeList nList = doc.getElementsByTagName("Livraison");
		         
		         //Seeing the Elements one by one for any possible Modification
		         for (int temp = 0; temp < nList.getLength(); temp++) {
		            Node nNode = nList.item(temp);
		            
		            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
		               Element eElement = (Element) nNode;
                               //Adding the Element information in our jTable         
                               model.addRow(new Object[]{eElement
                                           .getElementsByTagName("Nom")
                                           .item(0).getTextContent(), 
                                            eElement
                                           .getElementsByTagName("Prenom")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Telephone")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Date")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Poids")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Taille")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Destination")
                                           .item(0).getTextContent(),
                                            eElement
                                           .getElementsByTagName("Etat")
                                           .item(0).getTextContent()
                                            });
                               }
		         }
		       
		      } catch (Exception ex) {
		         ex.printStackTrace();
		      }

        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
