/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transapp;

import java.io.IOException;


import javax.swing.JOptionPane;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;
/**
 *
 * @author mohamed chagour
 */
public class Insert extends javax.swing.JFrame {

    /**
     * Creates new form Insert
     */
    
    static int x=(int) (1000*Math.random());
    
    public Insert() {
        initComponents();
        this.setTitle("Submit");
	this.setSize(930,570);
	this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(662, 387));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(339, 21, 60, 32);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(419, 156, 267, 32);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-10g", "11-50g", "51-100g", "100-1000g", "1-10Kg", "10Kg et plus" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(423, 204, 126, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Petit", "Moyen", "Grand", "Géant" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(423, 250, 139, 29);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date de prise:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(274, 152, 120, 32);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(419, 25, 267, 32);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prenom:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(313, 63, 86, 32);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(419, 67, 267, 32);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Téléphone:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 105, 111, 32);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(419, 109, 267, 32);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Poids:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(302, 199, 111, 32);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Taille:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(302, 250, 111, 32);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Etat:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(307, 347, 111, 32);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 21)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Destination:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(274, 293, 111, 32);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(419, 297, 267, 32);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Attendant de Packet", "En Cours", "Paquet chez le destinataire" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(422, 347, 126, 30);

        jButton2.setText("Ajouter");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(79, 23));
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(344, 402, 88, 35);

        jButton3.setText("Retour");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(79, 23));
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(438, 402, 94, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 94, 1054, 483);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1054, 88);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().length()==0 || 
                jTextField2.getText().length()==0 || 
                jTextField6.getText().length()==0 || 
                jTextField7.getText().length()==0 || 
                jTextField8.getText().length()==0){
				 JOptionPane.showMessageDialog(null, "Vous devez remplir tous les coordonnée");
			  
			 }
			 else{
				 
				 //--------------------------------------------------------------------------
				 
				 try {
                                                //Take the first Element in the XML Document
						Element students = d.getDocumentElement();
                                                //Create the Element in the Document
						Element student = d.createElement("Livraison");
						
                                                //Set the Attribute X to the Element
						student.setAttribute("code", Integer.toString(x));
                                                //Append the ChildElement in the Child Parent
						appendElement(student, Nom, jTextField6.getText());
						appendElement(student, Prenom, jTextField7.getText());
						appendElement(student, Telephone, jTextField8.getText());
						appendElement(student, Date, jTextField1.getText());
						appendElement(student, Taille, jComboBox1.getSelectedItem().toString());
						appendElement(student, Poids, jComboBox3.getSelectedItem().toString());
						appendElement(student, Destination, jTextField2.getText());
						appendElement(student, Etat, jComboBox4.getSelectedItem().toString());
						
                                                //Append this one in the global Element
						students.appendChild(student);
                                                
                                                //Methode For saving the changes
						saveXMLContent(d, FILE_PATH);

					} catch (Exception ex) {
						ex.printStackTrace();
					}
				 
				 
				 //Show you your code if you want to save it  
				 JOptionPane.showMessageDialog(null, "                Votre Code est: "+x +" \nvous pouvez consulter l'état de votre paquet ");
				 
                                 //Make les TextField Null After the Insert
				 jTextField6.setText("");
				 jTextField7.setText("");
				 jTextField8.setText("");
				 jTextField1.setText("");
				 jTextField2.setText("");
                                 
				 //Focusing on the First Field for a new Client
                                 jTextField6.requestFocus();
			 	}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Welcome W=new Welcome();
        W.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }
    
    //--------------------------------------------------------------------------------------------
                //Link for the XML File
	 	public static final String FILE_PATH = "input.xml";
		//Name of the INPUT
		public static final String Nom = "Nom";
		public static final String Prenom = "Prenom";
		public static final String Telephone = "Telephone";
		public static final String Date = "Date";
		public static final String Taille = "Taille";
		public static final String Poids = "Poids";
		public static final String Destination = "Destination";
		public static final String Etat = "Etat";
		
                //Our Document
		static Document d = getDocument(FILE_PATH);
		
		//Function to get the Document
		public static Document getDocument(String pathToFile) {
			Document d = null;

			DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
			DocumentBuilder db;
			try {
				db = dbf.newDocumentBuilder();
				d = db.parse(pathToFile);
			} catch (ParserConfigurationException e) {
				System.out.println("parser configuration exception");
				e.printStackTrace();
			} catch (SAXException | IOException e) {
				System.out.println("io or SAX exception");
				e.printStackTrace();
			}
			return d;
		}
		
                //Append the ChildElement in the ParentELemnt
		public static void appendElement(Element parentElement, String childName, String childValue) {
				Element id = d.createElement(childName);
				id.appendChild(d.createTextNode(childValue));
				parentElement.appendChild(id);
			}
		    
                //The Saving Method
                public static void saveXMLContent(Document d, String pathToFile) {
			try {
				TransformerFactory tff = TransformerFactory.newInstance();
				tff.setAttribute("indent-number", new Integer(2));
				Transformer tf = tff.newTransformer();
				tf.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");
				tf.setOutputProperty(OutputKeys.INDENT, "yes");
				DOMSource ds = new DOMSource(d);

				StreamResult sr = new StreamResult(pathToFile);
				DOMSource source = new DOMSource(d);
				tf.transform(ds, sr);

			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	 
	 
	 //--------------------------------------------------------------------------------------------
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
